### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by grayxr** [shspage/paperjs-pressure-pdfout#1]
Hi, I'm developing an app that uses pressure sensitivity data with Paper js and I came across this repository when searching online about how to implement it, would you mind if I used your approach (at least for now) for applying pressure sensitive data with paper js? I didn't see a license for this project. I plan on releasing my application later on, maybe this year, and it will probably be used in conjunction with another commercial application. Thanks!

**Comment by shspage** [comment]
Thank you for having interest in this one, and I'm sorry for the inconvenience..
I'll add license file to this repository after I come home tonight.
It'll be the same as paper.js (MIT).
Thanks.

**Comment by shspage** [comment]
I added license information.  Please let me know if I am missing something.
Thanks.

**Comment by grayxr** [comment]
No problem, thanks a lot!
